CREATE TABLE IF NOT EXISTS customers
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR                                 NOT NULL,
    email VARCHAR                                 NOT NULL UNIQUE,
    phone VARCHAR                                 NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT name_is_blank CHECK (name NOT LIKE ' ' AND name NOT LIKE ''),
    CONSTRAINT email_is_not_correct CHECK (email LIKE '%@%'),
    CONSTRAINT phone_is_blank CHECK (phone NOT LIKE ' ' AND phone NOT LIKE '')
);

CREATE TABLE IF NOT EXISTS orders
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id         BIGINT                                  NOT NULL,
    persons_number      BIGINT                                  NOT NULL,
    comments            VARCHAR                                 NOT NULL,
    address             VARCHAR                                 NOT NULL,
    apartment_or_office VARCHAR                                 NOT NULL,
    payment_type        VARCHAR                                 NOT NULL,
    operator_call       BOOLEAN                                 NOT NULL,
    condition_agreement BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id),
    CONSTRAINT comments_is_blank CHECK (comments NOT LIKE ' ' AND comments NOT LIKE ''),
    CONSTRAINT address_is_blank CHECK (address NOT LIKE ' ' AND address NOT LIKE ''),
    CONSTRAINT apartmentOrOffice_is_blank CHECK (apartment_or_office NOT LIKE ' ' AND apartment_or_office NOT LIKE ''),
    CONSTRAINT paymentType_is_blank CHECK (payment_type NOT LIKE ' ' AND payment_type NOT LIKE ''),
    CONSTRAINT fk_orders_to_customers FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS order_food
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id BIGINT                                  NOT NULL,
    food_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_order_food PRIMARY KEY (id),
    CONSTRAINT fk_order_food_to_orders FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE
);
